# Any ${VARIABLE} in this file will be replaced with the value from the .env file that should be in the same directory as `docker-compose.yaml`

services:  
  omni:
    image: ghcr.io/siderolabs/omni:v0.51.0
    container_name: omni
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 50180:50180/udp
    env_file: .env
    command:
      - --account-id=${OMNI_ACCOUNT_ID} 
      - --name=onprem-omni
      - --private-key-source=file:///omni.asc
      - --event-sink-port=8091
      - --bind-addr=0.0.0.0:4443
      - --machine-api-bind-addr=0.0.0.0:8090
      - --k8s-proxy-bind-addr=0.0.0.0:8100
      - --advertised-api-url=https://omni.${DOMAIN}
      - --siderolink-api-advertised-url=https://omni.${DOMAIN}:8090/
      - --siderolink-wireguard-advertised-addr=omni.${DOMAIN}:50180
      - --advertised-kubernetes-proxy-url=https://omni.${DOMAIN}:8100/
      - --auth-auth0-enabled=true
      - --auth-auth0-domain=${AUTH0_DOMAIN}
      - --auth-auth0-client-id=${AUTH0_CLIENT_ID}
      - --workload-proxying-subdomain=omni
      - --initial-users=${OMNI_INITIAL_USER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omni.rule=Host(`omni.${DOMAIN}`)"
      - "traefik.http.routers.omni.entrypoints=websecure"
      - "traefik.http.routers.omni.tls=true"
      - "traefik.http.routers.omni.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.omni.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.omni.loadbalancer.server.port=4443"
      - "traefik.http.services.omni.loadbalancer.server.scheme=https"
      # Omni API routing rule for consolidated routing
      - "traefik.http.routers.mapi.rule=Host(`omni.${DOMAIN}`) || Host(`192.168.1.17`)"
      - "traefik.http.routers.mapi.entrypoints=mapi"
      - "traefik.http.routers.mapi.tls=true"
      - "traefik.http.routers.mapi.tls.domains[0].main=omni.${DOMAIN}"
      - "traefik.http.services.mapi.loadbalancer.server.port=8090"
      - "traefik.http.services.mapi.loadbalancer.server.scheme=h2c"
      # Omni Kube routing rule for consolidated routing
      - "traefik.http.routers.kproxy.rule=Host(`omni.${DOMAIN}`)"
      - "traefik.http.routers.kproxy.entrypoints=kproxy"
      - "traefik.http.routers.kproxy.tls=true"
      - "traefik.http.routers.kproxy.tls.domains[0].main=omni.${DOMAIN}"
      - "traefik.http.services.kproxy.loadbalancer.server.port=8100"
      - "traefik.http.services.kproxy.loadbalancer.server.scheme=http"
    volumes:
      - ./omni:/_out
      - ./omni/omni.asc:/omni.asc:ro
    networks:
      - ipv6


  traefik:
    container_name: traefik
    image: traefik:v3.4.1
    restart: always
    env_file: .env
    command:
      - --providers.docker=true
      - --api.dashboard=true
      - --log.level=INFO
      - --log.filePath=/var/log/traefik.log
      - --serversTransport.insecureSkipVerify=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entryPoints.mapi.address=:8090
      - --entryPoints.kproxy.address=:8100
    environment:
      - TRAEFIK_TLS_CERTIFICATES_0_CERTFILE=/certs/cert.pem
      - TRAEFIK_TLS_CERTIFICATES_0_KEYFILE=/certs/privkey.pem
    ports:
      - "8080:80"     # plain http (optional if you redirect everything)
      - "8443:443"    # https for all your routers
      - "8090:8090"   # Omni machine-API
      - "8100:8100"   # Omni kube-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
      - "./traefik/logs:/var/log"
    labels:
      # Dashboard
      - "traefik.enable=true"
      - 'traefik.http.routers.traefik.rule=Host(`traefik-rpi1.${DOMAIN}`)'
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - 'traefik.http.routers.traefik.middlewares=strip'
      - 'traefik.http.middlewares.strip.stripprefix.prefixes=/traefik'
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    extra_hosts: 
      - host.docker.internal:172.19.0.1
    networks:
      - ipv6

networks:
  ipv6:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
